service:
  name: loggit-web-v2

useDotEnv: true

myNextAppplication:
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    domain: ['app', 'loggit.net']
    bucketName: loggit-web-v2
    bucketRegion: us-east-1
